from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.output_parsers import StrOutputParser

from config import (
    LLM_MODEL,
    TEMPERATURE,
)

from prompts import QA_PROMPT


def ask_question(question: str, retriever):
    """
    Retrieves relevant documents and generates
    an answer using Gemini.

    Parameters
    ----------
    question : str
        User question.

    retriever
        Chroma Retriever.

    Returns
    -------
    answer : str
        Final answer generated by the LLM.

    retrieved_docs : list
        Documents retrieved from Chroma.
    """

    # Retrieve relevant documents
    retrieved_docs = retriever.invoke(question)

    # Convert Documents into Context
    context = "\n\n".join(
        doc.page_content
        for doc in retrieved_docs
    )

    # Initialize Gemini
    llm = ChatGoogleGenerativeAI(
        model=LLM_MODEL,
        temperature=TEMPERATURE
    )

    # Output Parser
    output_parser = StrOutputParser()

    # Create Chain
    chain = QA_PROMPT | llm | output_parser

    # Generate Answer
    answer = chain.invoke(
        {
            "context": context,
            "question": question
        }
    )

    return answer, retrieved_docs